import { useData } from "../context/DataContext.jsx";
import { motion } from "framer-motion";

export default function ActivityPage() {
  const { logs } = useData();

  return (
    <motion.div
      className="space-y-6"
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
    >
      {}
      <div>
        <h2 className="text-2xl font-bold text-textDark">System Activity</h2>
        <p className="text-sm text-textMuted">
          Log of events generated by user actions and system processes.
        </p>
      </div>

      {}
      <div className="rounded-2xl border border-white/5 bg-cardDark overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left border-collapse">
            <thead>
              <tr className="text-[10px] text-textMuted uppercase tracking-widest bg-white/[0.02] border-b border-white/5 font-bold">
                <th className="py-4 px-6">Date</th>
                <th className="py-4 px-6">User</th>
                <th className="py-4 px-6">Action</th>
                <th className="py-4 px-6">Details</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5 font-medium">
              {logs && logs.length > 0 ? (
                logs.map((l) => (
                  <tr key={l.id} className="hover:bg-white/[0.01] transition-colors group">
                    <td className="py-4 px-6 text-textMuted">{l.date}</td>
                    <td className="py-4 px-6 text-textDark">{l.user}</td>
                    <td className="py-4 px-6 text-primary">{l.action}</td>
                    <td className="py-4 px-6 text-textMuted group-hover:text-textDark transition-colors">
                      {l.detail}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="4" className="text-center py-16 text-textMuted italic">
                    No activity logs found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </motion.div>
  );
}