import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { supabase } from "../supabase/client";

export default function ActivityPage() {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchActivity() {
      try {
        setLoading(true);
        const [clientsRes, productsRes, ordersRes] = await Promise.all([
          supabase.from('clients').select('*').order('created_at', { ascending: false }).limit(10),
          supabase.from('products').select('*').order('created_at', { ascending: false }).limit(10),
          supabase.from('orders').select('*').order('created_at', { ascending: false }).limit(10)
        ]);
        const clientLogs = (clientsRes.data || []).map(c => ({
          id: `client-${c.id}`,
          originalDate: c.created_at,
          date: new Date(c.created_at).toLocaleString(),
          user: "Admin",
          action: "New Client Registered",
          detail: `Client: ${c.name} (${c.country})`,
          type: "client"
        }));

        const productLogs = (productsRes.data || []).map(p => ({
          id: `prod-${p.id}`,
          originalDate: p.created_at,
          date: new Date(p.created_at).toLocaleString(),
          user: "Inventory Mgr",
          action: "Product Added",
          detail: `${p.name} added to ${p.category}`,
          type: "product"
        }));

        const orderLogs = (ordersRes.data || []).map(o => ({
          id: `order-${o.id}`,
          originalDate: o.created_at,
          date: new Date(o.created_at).toLocaleString(),
          user: "Sales System",
          action: "New Order Received",
          detail: `Order #${o.id} - Total: $${o.total}`,
          type: "order"
        }));
        const allActivity = [...clientLogs, ...productLogs, ...orderLogs].sort(
          (a, b) => new Date(b.originalDate) - new Date(a.originalDate)
        );

        setLogs(allActivity);

      } catch (error) {
        console.error("Error fetching activity:", error);
      } finally {
        setLoading(false);
      }
    }

    fetchActivity();
  }, []);

  const getActionColor = (type) => {
    switch (type) {
      case "order": return "text-emerald-500";
      case "client": return "text-blue-500";
      case "product": return "text-orange-500";
      default: return "text-primary";
    }
  };

  return (
    <motion.div
      className="space-y-6"
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
    >

      <div>
        <h2 className="text-2xl font-bold text-textDark">System Activity</h2>
        <p className="text-sm text-textMuted">
          Real-time log of events generated by system processes.
        </p>
      </div>

      {/* Table Container */}
      <div className="rounded-2xl border border-white/5 bg-cardDark overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left border-collapse">
            <thead>
              <tr className="text-[10px] text-textMuted uppercase tracking-widest bg-white/[0.02] border-b border-white/5 font-bold">
                <th className="py-4 px-6">Date & Time</th>
                <th className="py-4 px-6">User / Source</th>
                <th className="py-4 px-6">Action</th>
                <th className="py-4 px-6">Details</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5 font-medium">
              {loading ? (
                 <tr>
                   <td colSpan="4" className="text-center py-12 text-textMuted animate-pulse">
                     Loading activity feed...
                   </td>
                 </tr>
              ) : logs.length > 0 ? (
                logs.map((l) => (
                  <tr key={l.id} className="hover:bg-white/[0.01] transition-colors group">
                    <td className="py-4 px-6 text-textMuted font-mono text-[10px] opacity-80">{l.date}</td>
                    <td className="py-4 px-6 text-textDark font-bold">{l.user}</td>
                    <td className={`py-4 px-6 font-bold ${getActionColor(l.type)}`}>
                      {l.action}
                    </td>
                    <td className="py-4 px-6 text-textMuted group-hover:text-textDark transition-colors">
                      {l.detail}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="4" className="text-center py-16 text-textMuted italic">
                    No activity logs found. Start by creating clients or orders.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </motion.div>
  );
}